#!/bin/bash

# Tries to find out which of the scripts belong to which of the objects
# Needs a simplified version of the mappings file generated by calling python parse_mapping.py > tmp/symbols.txt

TMC_FOLDER="../github"
SCRIPTS_FOLDER="$TMC_FOLDER/data/scripts"

# Read symbols file
declare -A SYMBOLS
# https://stackoverflow.com/a/25251400
readarray -t lines < "tmp/symbols.txt"
for line in "${lines[@]}"; do
   key=${line%%:*}
   value=${line#*:}
   SYMBOLS[$key]=$value
done
#echo ${SYMBOLS[EzloCap]}

FILES=`ls $SCRIPTS_FOLDER`

for FILE in $FILES
do
    FILE_PATH="$SCRIPTS_FOLDER/$FILE"
    CALLED_FUNCTIONS=`grep -E "Call |CallWithArg " $FILE_PATH | cut -d " " -f 2 | sort | uniq | tr -d ","`
    echo "--- $FILE ---"
    LOCATIONS=""
    for FUNCTION in $CALLED_FUNCTIONS
    do
        #echo "-$FUNCTION"
        LOCATIONS="$LOCATIONS\n${SYMBOLS[$FUNCTION]}"
    done

    echo -e "$LOCATIONS" | sort | uniq | grep -Ev "^$|asm/code_|src/script.o"
done